### ISSUE TITLE
Backlog: Add change-scroll-region (CSR) and re-introduce scroll commands

### ISSUE THREAD

**Issue by imdaveho** [imdaveho/tuitty#14]
**Problem to Solve**
Scrolling puts too many things into the buffer and often, will flush due to the input buffer reaching capacity. This, not only causes unwanted behavior, but also needlessly renders too many things at once. Similar to issue #11 this will attempt to minimize the amount of "work" that `flush()` has to do, and only output the necessary parts of the terminal that needs to change.

**Tasks**
* [ ] add back scrolling ( `^[ Pn T` (down) and `^[ Pn S` (up) )
* [ ] add change scroll region ( `^[ Pn; Pn r` to set row start and row end as scrollable and `^[r` to reset )
* [ ] insert line and delete line to account for the clipped portions (this will reduce the amount written to stdout)

**Comment by imdaveho** [comment]
WinAPI: 

https://docs.microsoft.com/en-us/windows/console/scrollconsolescreenbuffer
