### ISSUE TITLE
Backlog: Detect window resize events

### ISSUE THREAD

**Issue by imdaveho** [imdaveho/tuitty#5]
**Problem to Solve**
If the user resizes the terminal window, there is nothing to detect how the contents should reflow, and more specifically, nothing to handle the changes in length and capacity for the contents in the stored screen buffer. It would also impact how we are recalculating internal cursor position, etc.

**Tasks**
* [ ] detect and handle SIGWINCH on Unix
* [ ] detect window resize events on Windows
* [ ] A. modify dispatch to specifically listen for this event 
  - meaning that `Dispatcher` must `init` already listening to `input_handler` thread (ie. no need to call `.listen()`
* [ ] B. as an `InputEvent` these changes can be handled by the User
  - might be more preferable as applications may want to handle the signal differently
